name: Send Daily INR Exchange Rates

on:
  schedule:
    # Runs at 9:00 AM UTC daily; adjust timezone as needed
    - cron: '0 9 * * *'

jobs:
  send_rates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Telegram Bot Script
     
      run: |
        python send_rates.py
